---
- name: Preparing system for deployment
  hosts: localhost

  tasks:
  - name: Checking for OS updates
    yum:
      name: '*'
      state: latest

  - name: Acquiring installation packages, verifying file integrity
    get_url:
      url: https://vcf-public.s3.us-east-2.amazonaws.com/atlassian-deployment-packages.tar.gz
      dest: /tmp/atlassian-deployment-packages.tar.gz
      # force: yes
      checksum: sha256:fa1acdef232fcc2a105c304949096cc5072dc2fe2e195c7eaeb6cbc3e35a1f09

  - name: Extracting packages from TAR archive
    unarchive:
      src: /tmp/atlassian-deployment-packages.tar.gz
      dest: /tmp

  - name: Instaling required dependencies
    yum:
      name: fontconfig
      state: latest



- name: Initiating Atlassian suite deployment
  hosts: localhost

  tasks:
  - name: Installing Jira v8.13.1
    shell: /tmp/atlassian-deployment-packages/atlassian-jira-software-8.13.1-x64.bin -q -varfile jira-response.varfile

  - name: Installing Confluence v7.8.3
    shell: /tmp/atlassian-deployment-packages/atlassian-confluence-7.8.3-x64.bin -q -varfile confluence-response.varfile

  - name: Installing BitBucket v7.7.0
    shell: /tmp/atlassian-deployment-packages/atlassian-bitbucket-7.7.0-x64.bin -q -varfile bitbucket-response.varfile



- name: Updating system security posture
  hosts: localhost

  tasks:
  - name: Opening local firewall ports for Jira
    firewalld:
      port: 8080/tcp
      permanent: yes
      zone: public
      state: enabled

  - name: Opening local firewall ports for Confluence
    firewalld:
      port: 8090/tcp
      permanent: yes
      zone: public
      state: enabled

  - name: Opening local firewall ports for BitBucket
    firewalld:
      port: 7990/tcp
      permanent: yes
      zone: public
      state: enabled
      
  - name: Opening local firewall ports for Elasticsearch
    firewalld:
      port: 7992-7993/tcp
      permanent: yes
      zone: public
      state: enabled


  - name: Bouncing local firewall
    systemd:
      name: firewalld
      state: reloaded
