---
- name: Preparing system for deployment
  hosts: localhost

  tasks:
  - name: Checking for OS updates
    yum:
      name: '*'
      state: latest

  - name: Acquiring installation packages, verifying file integrity
    get_url:
      url: https://vcf-public.s3.us-east-2.amazonaws.com/atlassian-deployment-packages.tar.gz
      dest: /tmp/atlassian-deployment-packages.tar.gz
      checksum: sha256:fa1acdef232fcc2a105c304949096cc5072dc2fe2e195c7eaeb6cbc3e35a1f09

  - name: Extracting packages from TAR archive
    unarchive:
      src: /tmp/atlassian-deployment-packages.tar.gz
      dest: /tmp

  - name: Instaling required dependencies
    yum:
      name: fontconfig
      state: latest



- name: Initiating Atlassian suite deployment
  hosts: localhost

  tasks:
  - name: Installing Jira v8.13.1
    shell: /tmp/atlassian-deployment-packages/atlassian-jira-software-8.13.1-x64.bin -q -varfile jira-response.varfile

  - name: Installing Confluence v7.8.3
    shell: /tmp/atlassian-deployment-packages/atlassian-confluence-7.8.3-x64.bin -q -varfile confluence-response.varfile

  - name: Installing BitBucket v7.7.0
    shell: /tmp/atlassian-deployment-packages/atlassian-bitbucket-7.7.0-x64.bin -q -varfile bitbucket-response.varfile



- name: Checking system security posture
  hosts: localhost

  tasks:
#   - name: Opening local firewall ports for Jira
#     firewalld:
#       port: 8080/tcp
#       zone: public
#       state: enabled
#       permanent: yes

#   - name: Opening local firewall ports for Confluence
#     firewalld:
#       port: 8090/tcp
#       zone: public
#       state: enabled
#       permanent: yes

#   - name: Opening local firewall ports for BitBucket
#     firewalld:
#       port: 7990/tcp
#       zone: public
#       state: enabled
#       permanent: yes

#   - name: Opening local firewall ports for Elasticsearch
#     firewalld:
#       port: 7992-7993/tcp
#       zone: public
#       state: enabled
#       permanent: yes

  - name: Bouncing local firewall
    systemd:
      name: firewalld
      state: stopped
      
#  - name: Installing SCAP
#    yum:
#     name: https://vcf-public.s3.us-east-2.amazonaws.com/scc-5.3.1.rhel7.x86_64.rpm
#     state: present
      
#  - name: Downloading SCAP
#    get_url:
#     url: https://vcf-public.s3.us-east-2.amazonaws.com/scc-5.3.1.rhel7.x86_64.rpm
#      dest: /tmp/scc-5.3.1.rhel7.x86_64.rpm

#  - name: Installing SCAP
#    shell: rpm -i /tmp/scc-5.3.1.rhel7.x86_64.rpm
#    warn: no

  - name: Executing SCAP scan
    shell: /opt/scc/cscc >> /var/log/scap-scan.log
    
  - name: Display completion message 
    debug:
      msg:
        - 'The automated Atlassian suite deployment has completed successfully.'
        - 'Deployment logs are located at /var/log/ansible.log and /var/log/atlassian-deployment.log'
        - 'SCAP scan results are located in /home/ansible/SCC/Sessions/'
        - 'Atlassian services are running on the following ports:'
        - 'Jira ===========> http://localhost:8080'
        - 'Confluence =====> http://localhost:8090'
        - 'BitBucket  =====> http://localhost:7990'
