---
- name: Play 1 -- Preparing system for deployment
  hosts: localhost

  tasks:
  - name: Checking for OS updates
    yum:
      name: '*'
      state: latest

  - name: Acquiring installation packages, verifying file integrity
    get_url:
      url: https://drive.google.com/file/d/1lrzw1qIVCFzd93sJaPx3SmfNUQ1IVSIs/view?usp=sharing
      dest: /tmp/atlassian-deployment-packages.tar.gz
      # checksum: sha256:486bcf2d84c2d7b48d8fe0e2a8f7c493e2d1d313c621f97cc2297617c9ca3a34

  - name: Extracting packages from TAR archive
    unarchive:
    src: /tmp/atlassian-deployment-packages.tar.gz
    dest: /tmp

  - name: Instaling required dependencies
    yum:
      name: fontconfig
      state: latest



- name: Play 2 -- Initiating Atlassian suite deployment
  hosts: localhost

  tasks:
  - name: Installing Jira v8.13.1
    shell: /tmp/atlassian-deployment-packages/atlassian-jira-software-8.13.1-x64.bin -q -varfile jira-response.varfile

  - name: Installing Confluence v7.8.3
    shell: /tmp/atlassian-deployment-packages/atlassian-confluence-7.8.3-x64.bin -q -varfile confluence-response.varfile

  - name: Installing BitBucket v7.7.0
    shell: /tmp/atlassian-deployment-packages/atlassian-bitbucket-7.7.0-x64.bin -q -varfile bitbucket-response.varfile



- name: Play 3 -- Updating system security posture
  hosts: localhost

  tasks:
  - name: Opening local firewall ports for Jira
    firewalld:
      port: 8080/tcp
      permanent: yes
      zone: public
      state: enabled

  - name: Opening local firewall ports for Confluence
    firewalld:
      port: 8090/tcp
      permanent: yes
      zone: public
      state: enabled

  # - name: Opening local firewall ports for BitBucket
  #   firewalld:
  #     port: 7990/tcp
  #     permanent: yes
  #     zone: public
  #     state: enabled

  - name: Opening local firewall ports for BitBucket
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    when: ansible_distribution == 'Red Hat Enterprise Linux'
    loop:
      - 7990/tcp
      - 7992/tcp
      - 7993/tcp

  - name: Bouncing local firewall
    systemd:
      name: firewalld
      state: reloaded
